FROM ubuntu:16.04
MAINTAINER "Manojvv" "manojv@ilimi.in"
RUN apt-get update && apt-get install -y git \
  unzip \
  zip \
  build-essential \
  curl
RUN mkdir -p /opt/mw
WORKDIR /opt/mw
COPY sunbird-mw.zip  /opt/mw/
RUN unzip /opt/mw/sunbird-mw.zip
WORKDIR /opt/mw/sunbird-mw/services/js-services/content_service
RUN curl --silent --location https://deb.nodesource.com/setup_6.x | bash - \
    && apt-get install --yes nodejs \
    && npm install --unsafe-perm
    && node app.js

