FROM mhart/alpine-node:6
MAINTAINER "Manojvv" "manojv@ilimi.in"
RUN apk update \
    && apk add zip \ 
    && mkdir -p /opt/content
ADD content /opt/content/
WORKDIR /opt/content/services/js-services/content_service/
RUN npm install --unsafe-perm
WORKDIR /opt
CMD ["zip", "-r", "content_service.zip", "content"]
